apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ui
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ui
  targetCPUUtilizationPercentage: 80
