apiVersion: v1
kind: Secret
metadata:
  name: orders-db
annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  url: "amRiYzptYXJpYWRiOi8vb3JkZXJzLW15c3FsOjMzMDYvb3JkZXJz"
  username: "b3JkZXJzX3VzZXI="
  password: "ZGVmYXVsdF9wYXNzd29yZA=="
