apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  DB_NAME: catalog
  DB_ENDPOINT: catalog-mysql:3306
  DB_READ_ENDPOINT: catalog-mysql:3306
