apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  REDIS_URL: redis://checkout-redis.checkout:6379
  ENDPOINTS_ORDERS: http://orders.orders.svc:80
